config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users do
    get '/follows' => 'relationships#follows', as: 'follows'
    get '/followers' => 'relationships#followers', as: 'followers'
  end
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'search#search'
  post 'follow/:id' => 'relationships#follow', as: 'follow' #フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' #フォロー外す
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new(book_comment_params)
    @book_comment.book_id = @book.id
		@book_comment.user_id = current_user.id
		unless @book_comment.save
		  render 'books/show'
		end
  end

  def destroy
    @book = Book.find(params[:book_id])
    book_comment = @book.book_comments.find(params[:id])
    book_comment.destroy
  end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_book_comment_index.html.erb
<% book_show.book_comments.each do |book_comment| %>
  <div>
    <tr>
      <td><%= attachment_image_tag(book_comment.user, :profile_image, size: "40x40", fallback: "no-image-icon.jpg") %></td>
          <td><%= book_comment.comment %></td>
          <% if current_user == book_comment.user %>
      	   <td><%= link_to 'Destroy', book_book_comment_path(book_comment.book.id, book_comment.id), class: 'btn-sm btn-danger',remote: true, method: :delete %></td>
    	    <% end %>
    	 </tr>
    	</div>
      <% end %>

app/views/book_comments/_user_book_comments.html.erb
<div class="container">
    <% books.each do |book| %>
  　<div class="row border rounded m-0 ">
    <div class="col-2 d-flex">
      <div class="m-auto">
        <%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, size: "40x40",  fallback: "no-image-icon.jpg") %>
      <% end %>
      </div>
    </div>
    <div class="col-10" id="book_<%= book.id%>">
        <p><%= link_to user_path(book.user) do %><%= book.user.name %><% end %></p>
        <p><%= link_to book_path(book.id) do %><%= book.body %><% end %></p>
       <div class="d-flex flex-row">
          <div class="favorite-btn d-inline p-2"><%= render "favorites/favorite-btn", book: book %></div>
          <div class="p-2 d-inline"> □<%= link_to book.book_comments.count, book_path(book) %></div>
       </div>
    </div>
    </div>
  <% end %>
</div>

app/views/book_comments/create.js.erb
$(".book_comments").html("<%= j(render "book_comments/book_comment_index", book_show: @book)%>");
$("#book_comment_comment").val(" ")
<!--なんで"#book_comment_comment"-->

app/views/book_comments/destroy.js.erb
$(".book_comments").html("<%= j(render "book_comments/book_comment_index", book_show: @book)%>");
$("#book_comment_comment").val(" ")
<!--なんで"#book_comment_comment"-->