config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users do
    get '/follows' => 'relationships#follows', as: 'follows'
    get '/followers' => 'relationships#followers', as: 'followers'
  end
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'search#search'
  post 'follow/:id' => 'relationships#follow', as: 'follow' #フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' #フォロー外す
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  # 検索用
  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book_show = Book.find(params[:id])
    @book = Book.new
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render "index"
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to books_path
  end

  def destroy_all
    Book.all.delete

  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model: book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<div class="container">
    <% books.each do |book| %>
  　<div class="row border rounded m-0 ">
    <div class="col-2 d-flex">
      <div class="m-auto">
      <%= link_to user_path(book.user) do %>
        <%= attachment_image_tag(book.user, :profile_image, size: "40x40",  fallback: "no-image-icon.jpg") %>
      <% end %>
      </div>
    </div>
    <div class="col-10" id="book_<%= book.id%>">
        <p><%= link_to user_path(book.user) do %><%= book.user.name %><% end %></p>
        <a href="/books/#{book.id}" class="stretched-link"><%= book.body %></a>

       <div class="d-flex flex-row">
          <div class="favorite-btn d-inline p-2"><%= render "favorites/favorite-btn", book: book %></div>
          <div class="p-2 d-inline"> □<%= link_to book.book_comments.count, book_path(book) %></div>
       </div>
      </div>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book_show.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>


  		  <div>
  		    <div><%= link_to "←", :back %></div>
  		    <h2>Book detail</h2>
  		  </div>
        <div class="border rounded">
            <div>
              <div><%= attachment_image_tag(@book_show.user, :profile_image, size: "40x40", fallback: "no-image-icon.jpg") %></div>
              <div><%= @book_show.user.name%></div>
              <% if @book_show.user_id == current_user.id %>
              <%= link_to 'Edit', edit_book_path(@book_show), class: "btn btn-sm btn-success edit_book_#{@book_show.id}" %>
              <%= link_to 'Destroy', book_path(@book_show), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%>
              <% end %>
            </div>
            <div>
              <div><%= @book_show.body %></div>
              <p><%= @book_show.created_at %></p>
            </div>
            <div class="d-flex flex-row" id="book_<%= @book_show.id%>">
              <div class="favorite-btn d-inline p-2"><%= render "favorites/favorite-btn", book: @book_show %></div>
              <div class="p-2 d-inline"> □<%= @book_show.book_comments.count %></div>
            </div>
        </div>


      <div class="book_comments">
        <%= render "book_comments/book_comment_index", book_show: @book_show %>
      </div>
      <div class="book_comments_form">
        <%= form_with model:[@book_show, @book_comment] do |f| %>
         <%= f.text_area :comment, size:"40x5" %>
         <%= f.submit '送信'%>
        <% end %>
      </div>
    </div>
  </div>
</div>